# Generated by Django 4.0.5 on 2022-06-30 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador del producto')),
                ('nombre', models.CharField(max_length=100, null=True, verbose_name='Nombre del producto')),
                ('descripcion', models.CharField(max_length=250, verbose_name='Descripcion del producto')),
                ('precio', models.IntegerField(verbose_name='Precio del producto')),
            ],
        ),
    ]
