# Generated by Django 4.0.5 on 2022-06-30 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador del cliente')),
                ('nombre', models.CharField(max_length=100, null=True, verbose_name='Nombre del cliente')),
                ('apellido', models.CharField(max_length=150, null=True, verbose_name='Apellido del cliente')),
                ('correo', models.CharField(max_length=200, null=True, verbose_name='Correo del cliente')),
                ('direccion', models.CharField(max_length=200, verbose_name='Direccion del cliente')),
            ],
        ),
    ]
